export default [
    {
      name: 'Div',
      type: 'div',
      config: {
        bgColor: 'orange',
        width: '50%',
        height: '50%',
        border: '0px solid black',
        borderRadius: '0px',
        boxShadow:0,
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        isScrollY: false,
        isScrollX: false,
        gap:'0px',
        marginLeft:'0px',
        marginRight:'0px',
        marginTop:'0px',
        marginBottom:'0px',
        position:'none',
      },
    },
    {
      name: 'Text',
      type: 'text',
      config: {
        bgColor: 'black',
        fontSize: '16px',
        fontFamily: 'Arial',
        fontWeight: '100',
        marginLeft:'0px',
        marginRight:'0px',
        marginTop:'0px',
        marginBottom:'0px',
        textContent:'Text',
      },
    },
    {
      name: 'Svg',
      type: 'svg',
      config: {
        width: "10%",
        height: "10%",
        bgColor: "black",
        svgName: "books",
        border: "none",
      },
    },
    {
      name: 'Image',
      type: 'image',
      config: {
        width: '25%',
        height: '10%',
        marginLeft:'0px',
        marginRight:'0px',
        marginTop:'0px',
        marginBottom:'0px', 
      },
    },
    {
      name: 'Button',
      type: 'button',
      config: {
        width: '30%',
        height: '15%',
        bgColor: '#b025ff',
        border: '0px solid black',
        fontSize:'10px',
        color: 'white',
        textContent: 'Button',
        marginLeft:'0px',
        marginRight:'0px',
        marginTop:'0px',
        marginBottom:'0px',    
      },
    },
    {
      name: 'Input',
      type: 'input',
      config: {
        width: '30%',
        height: '5%',
        bgColor: 'black',
        pxBorder:'1px',
        typeBorder: 'solid',
        colorBorder:'#606263',
        fontSize:'14px',
        color: 'white',
        fontFamily: 'Arial',
        fontWeight: '100',
        borderRadius: '0px',
        marginLeft:'0px',
        marginRight:'0px',
        marginTop:'0px',
        marginBottom:'0px',  
        textContent: 'placeholder...',  
      },
    },
    {
      name: 'Scroll list',
      type: 'div',
      config: {},
    }
  ];